// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gomq.proto

/*
Package routeguide is a generated protocol buffer package.

It is generated from these files:
	gomq.proto

It has these top-level messages:
	Identification
	Record
	Subscription
	Key
	PublishRecord
	Result
	Message
*/
package routeguide

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Identification struct {
	ConsumerID string `protobuf:"bytes,1,opt,name=consumerID" json:"consumerID,omitempty"`
}

func (m *Identification) Reset()                    { *m = Identification{} }
func (m *Identification) String() string            { return proto.CompactTextString(m) }
func (*Identification) ProtoMessage()               {}
func (*Identification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Identification) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

type Record struct {
	Key   *Key     `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value *Message `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Record) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Record) GetValue() *Message {
	if m != nil {
		return m.Value
	}
	return nil
}

type Subscription struct {
	Key        *Key   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	ConsumerID string `protobuf:"bytes,2,opt,name=consumerID" json:"consumerID,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Subscription) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Subscription) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

type Key struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Key) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PublishRecord struct {
	Key     *Key   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *PublishRecord) Reset()                    { *m = PublishRecord{} }
func (m *PublishRecord) String() string            { return proto.CompactTextString(m) }
func (*PublishRecord) ProtoMessage()               {}
func (*PublishRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PublishRecord) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PublishRecord) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Result struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Message struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Payload   []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Identification)(nil), "routeguide.Identification")
	proto.RegisterType((*Record)(nil), "routeguide.Record")
	proto.RegisterType((*Subscription)(nil), "routeguide.Subscription")
	proto.RegisterType((*Key)(nil), "routeguide.Key")
	proto.RegisterType((*PublishRecord)(nil), "routeguide.PublishRecord")
	proto.RegisterType((*Result)(nil), "routeguide.Result")
	proto.RegisterType((*Message)(nil), "routeguide.Message")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RouteGuide service

type RouteGuideClient interface {
	Publish(ctx context.Context, in *PublishRecord, opts ...grpc.CallOption) (*Result, error)
	Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Result, error)
	Unsubscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Result, error)
	Observe(ctx context.Context, in *Identification, opts ...grpc.CallOption) (RouteGuide_ObserveClient, error)
}

type routeGuideClient struct {
	cc *grpc.ClientConn
}

func NewRouteGuideClient(cc *grpc.ClientConn) RouteGuideClient {
	return &routeGuideClient{cc}
}

func (c *routeGuideClient) Publish(ctx context.Context, in *PublishRecord, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/routeguide.RouteGuide/Publish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/routeguide.RouteGuide/Subscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) Unsubscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/routeguide.RouteGuide/Unsubscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) Observe(ctx context.Context, in *Identification, opts ...grpc.CallOption) (RouteGuide_ObserveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RouteGuide_serviceDesc.Streams[0], c.cc, "/routeguide.RouteGuide/Observe", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideObserveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RouteGuide_ObserveClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type routeGuideObserveClient struct {
	grpc.ClientStream
}

func (x *routeGuideObserveClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RouteGuide service

type RouteGuideServer interface {
	Publish(context.Context, *PublishRecord) (*Result, error)
	Subscribe(context.Context, *Subscription) (*Result, error)
	Unsubscribe(context.Context, *Subscription) (*Result, error)
	Observe(*Identification, RouteGuide_ObserveServer) error
}

func RegisterRouteGuideServer(s *grpc.Server, srv RouteGuideServer) {
	s.RegisterService(&_RouteGuide_serviceDesc, srv)
}

func _RouteGuide_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routeguide.RouteGuide/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).Publish(ctx, req.(*PublishRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routeguide.RouteGuide/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).Subscribe(ctx, req.(*Subscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routeguide.RouteGuide/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).Unsubscribe(ctx, req.(*Subscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_Observe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Identification)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteGuideServer).Observe(m, &routeGuideObserveServer{stream})
}

type RouteGuide_ObserveServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type routeGuideObserveServer struct {
	grpc.ServerStream
}

func (x *routeGuideObserveServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

var _RouteGuide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "routeguide.RouteGuide",
	HandlerType: (*RouteGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _RouteGuide_Publish_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _RouteGuide_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _RouteGuide_Unsubscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Observe",
			Handler:       _RouteGuide_Observe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gomq.proto",
}

func init() { proto.RegisterFile("gomq.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcb, 0x4b, 0xc3, 0x40,
	0x10, 0xc6, 0xdb, 0xd4, 0x36, 0x74, 0x5a, 0x2b, 0x8c, 0x97, 0x58, 0x8a, 0x8f, 0x3d, 0xe9, 0xa5,
	0x94, 0x7a, 0x53, 0xbc, 0x09, 0x52, 0xaa, 0x68, 0x23, 0x7a, 0xcf, 0x63, 0xac, 0x8b, 0x49, 0x36,
	0x66, 0x37, 0x85, 0x9c, 0xfd, 0xc7, 0x25, 0xdb, 0x94, 0x6e, 0x14, 0xa1, 0xe0, 0x2d, 0x3b, 0xf3,
	0xcd, 0xcc, 0xef, 0x9b, 0x0c, 0xc0, 0x52, 0xc4, 0x9f, 0xe3, 0x34, 0x13, 0x4a, 0x20, 0x64, 0x22,
	0x57, 0xb4, 0xcc, 0x79, 0x48, 0x6c, 0x02, 0x83, 0x59, 0x48, 0x89, 0xe2, 0x6f, 0x3c, 0xf0, 0x14,
	0x17, 0x09, 0x1e, 0x03, 0x04, 0x22, 0x91, 0x79, 0x4c, 0xd9, 0xec, 0xd6, 0x69, 0x9e, 0x36, 0xcf,
	0xbb, 0xae, 0x11, 0x61, 0xaf, 0xd0, 0x71, 0x29, 0x10, 0x59, 0x88, 0x67, 0xd0, 0xfa, 0xa0, 0x42,
	0x4b, 0x7a, 0xd3, 0x83, 0xf1, 0xb6, 0xeb, 0x78, 0x4e, 0x85, 0x5b, 0xe6, 0xf0, 0x02, 0xda, 0x2b,
	0x2f, 0xca, 0xc9, 0xb1, 0xb4, 0xe8, 0xd0, 0x14, 0x3d, 0x90, 0x94, 0xde, 0x92, 0xdc, 0xb5, 0x82,
	0x2d, 0xa0, 0xff, 0x9c, 0xfb, 0x32, 0xc8, 0x78, 0xaa, 0x39, 0x76, 0xe8, 0x5e, 0x47, 0xb5, 0x7e,
	0xa1, 0x9e, 0x40, 0x6b, 0x4e, 0x05, 0x3a, 0x60, 0x07, 0x22, 0x51, 0x94, 0xa8, 0xca, 0xce, 0xe6,
	0xc9, 0xee, 0x61, 0xff, 0x29, 0xf7, 0x23, 0x2e, 0xdf, 0x77, 0xb7, 0xe4, 0x80, 0x9d, 0x7a, 0x45,
	0x24, 0xbc, 0x50, 0x4f, 0xec, 0xbb, 0x9b, 0x27, 0x1b, 0x95, 0x9b, 0x91, 0x79, 0xa4, 0x10, 0x61,
	0x2f, 0x10, 0x21, 0xe9, 0x3e, 0x6d, 0x57, 0x7f, 0xb3, 0x05, 0xd8, 0x95, 0x63, 0x1c, 0x80, 0xc5,
	0xc3, 0x8a, 0xc5, 0xe2, 0x21, 0x8e, 0xa0, 0xab, 0x78, 0x4c, 0x52, 0x79, 0x71, 0x5a, 0xd9, 0xd8,
	0x06, 0xcc, 0x81, 0xad, 0xda, 0xc0, 0xe9, 0x97, 0x05, 0xe0, 0x96, 0x88, 0x77, 0x25, 0x22, 0x5e,
	0x81, 0x5d, 0xb9, 0xc1, 0x23, 0x13, 0xbd, 0x66, 0x71, 0x88, 0x66, 0x6a, 0xcd, 0xcb, 0x1a, 0x78,
	0x0d, 0xdd, 0x6a, 0xfb, 0x3e, 0xa1, 0x63, 0x4a, 0xcc, 0x9f, 0xf2, 0x47, 0xf1, 0x0d, 0xf4, 0x5e,
	0x12, 0xf9, 0x8f, 0x72, 0xfb, 0xd1, 0x97, 0x94, 0xad, 0x08, 0x87, 0xa6, 0xa0, 0x7e, 0x98, 0x3f,
	0x8b, 0x4b, 0x33, 0xac, 0x31, 0x69, 0xfa, 0x1d, 0x7d, 0xd5, 0x97, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x26, 0xe5, 0x08, 0x0f, 0xe3, 0x02, 0x00, 0x00,
}
